### ISSUE TITLE
Nginx with SSL

### ISSUE THREAD

**Issue by S0PEX** [xfrocks/docker-xenforo#10]
Hey and thanks for this repo,

so I am currently trying to move my xenforo to docker. And I got everything up and running under nginx, PHP-fpm but for some reason, I cannot get my Cloudflare ssl working. I already added the variables needed for the nginx-proxy.
```yml
nginx:
    image: xfrocks/xenforo:nginx
    environment:
      - NGINX_ACCESS_LOG_FORMAT=timed
      - NGINX_FAST_CGI_PASS=php-fpm:9000
      - VIRTUAL_HOST=mydomain.com
      - VIRTUAL_PROTO=https
```

But for some odd reason, the requests are not forwarded correctly.
Might you have a clue?

Regards Artur
