### ISSUE TITLE
Working example for Nginx with php8?

### ISSUE THREAD

**Issue by EinHecki** [xfrocks/docker-xenforo#25]
Hi, is there any fully working docker-compose example for nginx with php8?

**Comment by daohoangson** [comment]
The latest is still php7. If you need php8 then consider the PR #24. But it's not completed though.

**Comment by EinHecki** [comment]
Okay, I now changed my `docker-compose.yml` to this:
```
version: '3.9'

services:

  src:
    image: alpine
    command: ["uptime"]
    volumes:
      - .:/var/www/html

  php-fpm:
    image: xfrocks/xenforo:php-fpm
    volumes_from:
      - src
    
  nginx:
    image: xfrocks/xenforo:nginx
    environment:
      - VIRTUAL_HOST=localhost
    expose:
      - "80"
    links:
      - php-fpm
    volumes_from:
      - src

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
```

But I'm getting a `502 Bad Gateway error`. Atm I'm trying this on my local Windows machine
